version: 0.4.{build}
image: Visual Studio 2017
environment:
  api_key:
    secure: N7pTAGzXcURTT9qQIKPx62XaO7xKEjUjhUC3/zcKv/Hd4qkcIPNdLqh1eJHHWJd3
branches:
  only:
  - master
skip_commits:
  message: /\[chore\]/
init:
  - git config --global core.autocrlf true
build_script:
- ps: >-
    dotnet restore

    $xmlPath = "$env:appveyor_build_folder\src\TstFxtr\TstFxtr.csproj"

    $xml = [xml](get-content $xmlPath)

    $propertyGroup = $xml.Project.PropertyGroup

    $propertyGroup.Version = $env:appveyor_build_version

    $xml.Save($xmlPath)

    dotnet build -c Release
test_script:
- ps: >-
    cd tests/tstfxtr.tests

    dotnet test -c Release --no-build
on_success:
- ps: >-
    if(!$env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
      nuget.exe setApiKey $env:api_key -source https://www.nuget.org
      nuget push "$env:appveyor_build_folder\src\TstFxtr\bin\Release\TstFxtr.$env:appveyor_build_version.nupkg" -source https://www.nuget.org/api/v2/package
    }