namespace TstFxtr
{
    public class LoremConstants
    {
        public const string Lorem1 = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";
        public const string Hairy = "El snort testosterone trophy driving gloves handsome, dis el snort handsome gent testosterone trophy Fallen eyebrow driving gloves cardinal richelieu gentleman face broom, chevron driving gloves dis cardinal richelieu gentleman gent el snort handsome ron burgundy Leonine funny walk groucho marx Fallen eyebrow rock n roll star great dictator testosterone trophy face broom?";
        public const string Web2 = "Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem plugg dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra. Babblely odeo kaboodle quora plaxo ideeli hulu weebly balihoo kno vimeo zlio voxy zinch twones zoodles joost, sococo zynga imvu imeem stypi lijit bubbli flickr mog sococo greplin bebo waze voxy. Spotify kno diigo sifteo dropio sococo chegg meevee empressr kosmix groupon handango, cloudera mzinga chartly plickers loopt xobni airbnb prezi vuvox jiglu omgpop, vimeo jumo eskobo omgpop jabber oooj mobly voki ngmoco blippy.";
        public const string Hipster = "Wes Anderson umami biodiesel YOLO, Terry Richardson helvetica tousled street art master cleanse selfies Godard cornhole 8-bit pork belly scenester. Blog blue bottle Neutra, polaroid pug cliche dreamcatcher. Ethnic wolf church-key, Wes Anderson tattooed meh tumblr direct trade literally jean shorts swag shabby chic chillwave DIY pug. Tousled lomo letterpress, flexitarian bitters Schlitz messenger bag Carles. Brooklyn shabby chic letterpress, gluten-free blog Etsy ennui umami cliche hashtag leggings hoodie bitters. Pickled scenester Austin craft beer, 3 wolf moon squid sriracha letterpress occupy. Flexitarian Odd Future semiotics, church-key lomo 8-bit ethnic artisan seitan brunch.";
        public const string Fillerama = "Take me to your leader! Switzerland is small and neutral! We are more like Germany, ambitious and misunderstood! And so we say goodbye to our beloved pet, Nibbler, who's gone to a place where I, too, hope one day to go. The toilet. Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.";
        public const string Arrested = "No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. He'll want to use your yacht, and I don't want this thing smelling like fish. No! I was ashamed to be SEEN with you. I like being with you. Get me a vodka rocks. And a piece of toast. Get me a vodka rocks. And a piece of toast.";
        public const string Bacon = "Bacon ipsum dolor sit amet tenderloin salami pig, fatback pastrami ham hock shoulder bacon t-bone pork meatball. Pancetta ham turkey shankle turducken jerky. Jowl spare ribs short ribs andouille tongue shoulder. Rump shoulder cow turducken, salami filet mignon ham sausage pancetta pork prosciutto brisket short ribs boudin. Shoulder short ribs andouille swine venison ham hock.";
        public const string Cupcake = "Candy bonbon pastry jujubes lollipop wafer biscuit biscuit. Topping brownie sesame snaps sweet roll pie. Croissant danish biscuit soufflé caramels jujubes jelly. Dragée danish caramels lemon drops dragée. Gummi bears cupcake biscuit tiramisu sugar plum pastry. Dragée gummies applicake pudding liquorice. Donut jujubes oat cake jelly-o. Dessert bear claw chocolate cake gummies lollipop sugar plum ice cream gummies cheesecake.";
        public const string Beer = "amber, microbrewery abbey hydrometer, brewpub ale lauter tun saccharification oxidized barrel. berliner weisse wort chiller adjunct hydrometer alcohol aau! sour/acidic sour/acidic chocolate malt ipa ipa hydrometer.";
        public const string Samuel = "The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.";
        public const string Corporate = "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI. Efficiently unleash cross-media information without cross-media value. Quickly maximize timely deliverables for real-time schemas. Dramatically maintain clicks-and-mortar solutions without functional solutions.";
        public const string Fillerati = "I opine, that it is plainly traceable to the first arrival of the Greenland whaling ships in London, more than two centuries ago. Because those whalemen did not then, and do not now, try out their oil at sea as the Southern ships have always done; but cutting up the fresh blubber in small bits, thrust it through the bung holes of large casks, and carry it home in that manner; the shortness of the season in those Icy Seas, and the sudden and violent storms to which they are exposed, forbidding any other course. The consequence is, that upon breaking into the hold, and unloading one of these whale cemeteries, in the Greenland dock, a savor is given forth somewhat similar to that arising from excavating an old city grave-yard, for the foundations of a Lying-in-Hospital.";
        public const string Zombie = "In omni memoria patriae religionis sunt diri undead historiarum. Golums, zombies et fascinati. Maleficia! Vel a modern perhsaps morbi. A terrenti contagium. Forsitan illud Apocalypsi, vel malum poenae horrifying fecimus. Indeflexus monstra per plateas currere. Fit de nostra carne undead. Poenitentiam agite pœnitentiam! Vivens mortua sunt apud nos.";
        public const string Gangster = "Maecenizzle mah nizzle mi. Nam bling bling. Pimpin' condimentizzle, check out this nizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle consectetuer, things libero doggy purus, fo shizzle mah nizzle fo rizzle, mah home g-dizzle shizznit the bizzle mah nizzle nizzle quam. Get down get down faucibizzle elit. Break it down nibh break yo neck, yall, yo mamma sizzle, fo shizzle my nizzle volutpizzle, mammasay mammasa mamma oo sa ac, yo. Prizzle sed urna. Gangsta ass the bizzle izzle fo shizzle. Pellentesque hendrerit euismizzle felizzle. Donec bling bling nisl shit erat. Etiam posuere yo mi. Ut maurizzle. Sed nisl metus, euismizzle ac, hizzle , i'm in the shizzle cool, nisi. Vivamus vulputate fo shizzle nisl.";
        public const string Journo = "Knight Foundation Bill Keller afternoon paper I love the Weather & Opera section bloggers in their mother's basement retweet analog thinking crowdsourcing, just across the wire David Cohn mthomps hyperhyperhyperlocal Wikipedia Does my 'yes, but' look big in this corner office? newspaper, the medium is the message tags tools Gardening & War section The Work of Art in the Age of Mechanical Reproduction got drudged. Demand Media put the paper to bed MinnPost going forward reality-based try PR WSJ Fuego John Dewey filters, location-based community I saw it on Mediagazer hyperhyperlocal Groupon curation Kindle Single.";
        public const string Cat = "Leave dead animals as gifts intently sniff hand yet chase imaginary bugs intently sniff hand. Under the bed throwup on your pillow all of a sudden go crazy destroy couch sweet beast. Inspect anything brought into the house stretch stretch. Sweet beast flop over flop over so burrow under covers. Lick butt use lap as chair for stick butt in face hopped up on goofballs hide when guests come over give attitude and all of a sudden go crazy. Mark territory stretch but intently sniff hand use lap as chair and all of a sudden go crazy so cat snacks yet stare at ceiling.";
        public const string Veggie = "Sea lettuce melon cabbage leek bamboo shoot lettuce rutabaga jícama silver beet amaranth pea dandelion scallion pea sprouts yarrow salsify bitterleaf courgette. Azuki bean horseradish potato kale welsh onion fennel green bean azuki bean chickweed aubergine bell pepper sea lettuce rutabaga cucumber grape. Radish grape rutabaga celery beetroot kombu spring onion cauliflower soybean.";
        public const string Picksum = "You see, in this world there's two kinds of people, my friend: those with loaded guns and those who dig. you dig. you see, in this world there's two kinds of people, my friend: those with loaded guns and those who dig. you dig. here. put that in your report! i may have found a way out of here. are you feeling lucky punk this is the ak-47 assault rifle, the preferred weapon of your enemy; and it makes a distinctive sound when fired at you, so remember it. you want a guarantee, buy a toaster. what you have to ask yourself is, do i feel lucky. well do ya' punk? here. put that in your report! i may have found a way out of here. you want a guarantee, buy a toaster. here. put that in your report!' and 'i may have found a way out of here. man's gotta know his limitations. don't p!ss down my back and tell me it's raining.";
        public const string Hodor = "Hodor! Hodor hodor, HODOR hodor, hodor hodor... Hodor hodor hodor hodor hodor hodor? Hodor, hodor. Hodor. Hodor, hodor... Hodor hodor hodor?! Hodor hodor, hodor. Hodor HODOR hodor, hodor hodor hodor! Hodor, hodor hodor hodor - hodor. Hodor. Hodor hodor hodor hodor hodor hodor hodor! Hodor, HODOR hodor, hodor hodor hodor hodor; hodor hodor. Hodor hodor HODOR! Hodor hodor hodor hodor hodor, hodor, hodor hodor.";
    }
}
